title: ADHDAI
description: An AI ad agency that generates the worst ads in the world.
url: ""
baseurl: ""

# Build settings
markdown: kramdown
theme: null
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
