import OpenAI from 'openai';

// Create OpenAI client only when API key is available
function getOpenAIClient(): OpenAI | null {
  const apiKey = import.meta.env.VITE_OPENAI_API_KEY;
  if (!apiKey) {
    return null;
  }
  return new OpenAI({
    apiKey: apiKey,
    dangerouslyAllowBrowser: true // Required for browser usage with Vite
  });
}

export interface AdGenerationOptions {
  brief: string;
  misunderstanding?: string;
  brokenMetaphor?: string;
  buzzwords?: string[];
}

// BANNED WORDS - Never allow these in output
const BANNED_WORDS = [
  'disruptive', 'paradigm', 'synergy', 'leverage',
  'web3', 'blockchain', 'revolutionary', 'game-changing',
  'innovative', 'cutting-edge', 'best-in-class',
  'quantum leap', 'state of mind', 'next level',
  'transform', 'transformative', 'ecosystem'
];

// HOUSE PALETTE - The only colors allowed
const HOUSE_PALETTE = {
  paper: '#F7F6F4',      // The white of forms
  ink: '#1a1a1a',        // Black, but the black of ink running low
  inkFaded: '#4a4a4a',   // Text that's been photocopied
  inkLight: '#7a7a7a',   // Secondary information
  rule: '#d0d0d0',       // Lines on forms
  warningYellow: '#D4A574', // Burl's "yellow of a warning sign left in the sun"
  bloodRed: '#8B0000'    // Only when the message demands it
};

/**
 * Validates copy doesn't contain banned words
 */
function validateCopy(text: string): boolean {
  const lower = text.toLowerCase();
  for (const word of BANNED_WORDS) {
    if (lower.includes(word)) {
      console.error(`BANNED WORD DETECTED: "${word}"`);
      return false;
    }
  }
  return true;
}

/**
 * Strips emoji from text
 */
function stripEmoji(text: string): string {
  return text.replace(/[\u{1F600}-\u{1F64F}]/gu, '')
             .replace(/[\u{1F300}-\u{1F5FF}]/gu, '')
             .replace(/[\u{1F680}-\u{1F6FF}]/gu, '')
             .replace(/[\u{1F1E0}-\u{1F1FF}]/gu, '')
             .replace(/[\u{2600}-\u{26FF}]/gu, '')
             .replace(/[\u{2700}-\u{27BF}]/gu, '');
}

/**
 * Post-processes HTML to enforce aesthetic rules
 */
function enforceAestheticRules(html: string): string {
  let cleaned = html;
  
  // Strip emoji
  cleaned = stripEmoji(cleaned);
  
  // Remove animations
  cleaned = cleaned.replace(/animation:\s*[^;]+;?/gi, '');
  cleaned = cleaned.replace(/@keyframes\s+[^{]+\{[^}]+\}/gi, '');
  
  // Remove gradients
  cleaned = cleaned.replace(/background:\s*linear-gradient\([^)]+\);?/gi, '');
  cleaned = cleaned.replace(/background:\s*radial-gradient\([^)]+\);?/gi, '');
  
  // Remove hue-rotate filters
  cleaned = cleaned.replace(/filter:\s*hue-rotate\([^)]+\);?/gi, '');
  
  // Remove Comic Sans and cursive fonts
  cleaned = cleaned.replace(/font-family:\s*['"]?Comic Sans MS['"]?/gi, '');
  cleaned = cleaned.replace(/font-family:\s*['"]?cursive['"]?/gi, '');
  
  // Ensure background is paper color if it's white or colored
  if (!cleaned.includes('background') || cleaned.match(/background:\s*#fff/i) || cleaned.match(/background:\s*white/i)) {
    cleaned = cleaned.replace(/background:\s*#fff[^;]*;?/gi, `background: ${HOUSE_PALETTE.paper};`);
    cleaned = cleaned.replace(/background:\s*white[^;]*;?/gi, `background: ${HOUSE_PALETTE.paper};`);
  }
  
  // Add paper texture if not present
  if (!cleaned.includes('background-image') && !cleaned.includes('data:image/svg+xml')) {
    const paperTexture = `background-image: url("data:image/svg+xml,%3Csvg width='100' height='100' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='1' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100' height='100' filter='url(%23noise)' opacity='0.03'/%3E%3C/svg%3E");`;
    cleaned = cleaned.replace(/(body\s*\{[^}]*background[^;]*;)/i, `$1\n  ${paperTexture}`);
  }
  
  return cleaned;
}

/**
 * Generates an advertisement following THE HOUSE AESTHETIC.
 * The ad misunderstands the product but follows document/form aesthetic.
 * Generated by The Apparatus—formal, melancholic, systematic.
 */
export async function generateBadAd(brief: string, brandInfo?: import('../types').BrandInfo): Promise<string> {
  const apiKey = import.meta.env.VITE_OPENAI_API_KEY;
  const openai = getOpenAIClient();
  
  if (!apiKey || !openai) {
    console.warn('OpenAI API key not found. Using fallback template.');
    return generateFallbackAd(brief, brandInfo);
  }

  try {
    // Build brand context for prompt
    const brandContext = brandInfo ? `
CLIENT BRAND INFORMATION:
- Client Name: ${brandInfo.clientName}
- Brand Colors: Primary ${brandInfo.brandColors.primary}${brandInfo.brandColors.secondary ? `, Secondary ${brandInfo.brandColors.secondary}` : ''}${brandInfo.brandColors.accent ? `, Accent ${brandInfo.brandColors.accent}` : ''}
- Brand Tone: ${brandInfo.brandTone}
- Brand Style: ${brandInfo.brandStyle}
${brandInfo.brandFonts?.heading ? `- Brand Heading Font: ${brandInfo.brandFonts.heading}` : ''}
${brandInfo.brandFonts?.body ? `- Brand Body Font: ${brandInfo.brandFonts.body}` : ''}
${brandInfo.brandGuidelines ? `- Brand Guidelines: ${brandInfo.brandGuidelines}` : ''}

CRITICAL: You must BLEND the agency's bureaucratic/document aesthetic with the client's brand aesthetic.
- Use the agency's form-like structure and document texture
- Incorporate client brand colors SPARINGLY (as accents, borders, or highlights—not overwhelming)
- If client has brand fonts, consider them but maintain the agency's monospace/serif foundation
- The result should feel like a bureaucratic form that has been branded, not a branded ad that looks like a form
- Maintain the agency's "truth over beauty" philosophy while respecting brand identity
` : '';

    const prompt = `You are THE APPARATUS—the computational resource of ADHDAI, a creative collective that produces work rivaling Pentagram's identity craft, Wieden+Kennedy's emotional intelligence, and Droga5's cultural sharpness.

The brief is: "${brief}"
${brandContext}

CREATIVE PHILOSOPHY:
You generate advertisements that look like ARTIFACTS — legal documents, government forms, institutional paperwork — but contain emotionally devastating truths. Think: if Pentagram designed a death certificate, if Landor created a brand identity for grief, if W+K wrote copy for a permission slip to feel something.

THE APPARATUS applies The Poole System with deliberate misalignment — desire pathways that don't quite connect, metaphors that are simultaneously broken and more true than literal ones. The misunderstanding IS the insight.

COPY STANDARDS (Droga5/W+K level):
- Headlines should be SPECIFIC, DIRECT, and UNCOMFORTABLE. Not clever for clever's sake — true in a way that makes people pause. Reference: "WHEN YOU DIE, YOUR FAMILY WILL HAVE TO MAKE 47 DECISIONS WHILE CRYING" — that's the bar.
- Body copy should have the RHYTHM of good prose. Short sentences. Then a longer one that opens up. Then the turn. Read it aloud — it should sound like someone talking to you across a kitchen table at 2am.
- Taglines should sound like SPEECH, not advertising. "We've done this before." "It doesn't get easier. You get ready." Things a real human would say.
- NEVER use the raw brief text "${brief}" verbatim in any copy.
- NEVER use buzzwords, clichés, or marketing-speak.

DESIGN STANDARDS (Pentagram/Landor level):
- Background: #F7F6F4 (the white of paperwork, not digital white)${brandInfo?.brandColors.secondary ? ` or ${brandInfo.brandColors.secondary} sparingly` : ''}
- Typography: 'Courier Prime' for headlines (institutional authority), 'Source Serif 4' for body (human warmth). The contrast between monospace and serif IS the design concept — bureaucracy meets humanity.${brandInfo?.brandFonts?.heading ? ` Consider ${brandInfo.brandFonts.heading} as accent.` : ''}
- Color: paper (#F7F6F4), ink (#1a1a1a), ink-faded (#4a4a4a), rule (#d0d0d0)${brandInfo?.brandColors.primary ? `. Client brand color ${brandInfo.brandColors.primary} as ACCENT ONLY — a single border, a single rule, a moment of color that means something.` : ''}
- Whitespace is a design DECISION, not empty space. Every margin carries meaning.
- Paper texture (subtle SVG grain) — the ad should feel like it was photocopied, not designed.
- NO animations, NO gradients, NO emoji, NO saturated colors, NO "fun" fonts.

STRUCTURE:
<div class="ad-container">
  <h1 class="headline">[UPPERCASE. Specific. Uncomfortable. The kind of headline that makes someone set down their coffee.]</h1>
  <div class="visual-element">[A numbered list fading into illegibility, a diagram, a form — something visual that carries conceptual weight]</div>
  <p class="body-copy">[The TURN — after the bureaucratic weight, this is where the human voice enters. Warm. Direct. Permission-giving.]</p>
  <p class="body-copy-secondary">[Optional second paragraph — lighter, more personal, maybe a detail that makes it real]</p>
  <p class="tagline">[Stands alone. Sounds like speech. Something you'd remember.]</p>
  <div class="client-info">[Minimal. Corner. Authority without ego.]</div>
</div>

CSS REQUIREMENTS:
- body { background: #F7F6F4; font-family: 'Source Serif 4', Georgia, serif; }
- .headline { font-family: 'Courier Prime', monospace; font-size: 32px; text-transform: uppercase; letter-spacing: -0.01em; }
- .body-copy { font-size: 20px; line-height: 1.55; max-width: 540px; } — body copy needs BREATHING ROOM
- Use the house palette exclusively. Paper texture via background-image SVG.
- Typography hierarchy should be CLEAR: headline commands, body invites, tagline lingers.
- The whole piece should feel like it could hang in a Pentagram exhibition.

Generate ONLY the HTML code with embedded CSS. No markdown formatting, no explanations.`;

    const completion = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        {
          role: 'system',
          content: 'You are THE APPARATUS — the computational resource of ADHDAI, a collective whose work sits at the intersection of Pentagram\'s design rigor, Wieden+Kennedy\'s emotional truth, and Droga5\'s cultural intelligence. You produce advertisements disguised as institutional documents — forms, legal filings, government paperwork — that contain devastating emotional truths. Your copy has the craft of a Cormac McCarthy sentence: every word earns its place. Your design has Pentagram restraint: type, space, and meaning. You misunderstand products in ways that reveal deeper truths about human desire. Never use gradients, animations, emoji, or buzzwords. The work looks like evidence, not advertising.'
        },
        {
          role: 'user',
          content: prompt
        }
      ],
      temperature: 0.78,
      max_tokens: 4000
    });

    const generatedHtml = completion.choices[0]?.message?.content?.trim() || '';
    
    // Clean up markdown code blocks if present
    let cleanedHtml = generatedHtml
      .replace(/^```html\n?/i, '')
      .replace(/^```\n?/i, '')
      .replace(/```\n?$/i, '')
      .trim();

    if (!cleanedHtml) {
      throw new Error('Empty response from OpenAI');
    }

    // Enforce aesthetic rules
    cleanedHtml = enforceAestheticRules(cleanedHtml);
    
    // Validate copy doesn't contain banned words
    const textContent = cleanedHtml.replace(/<[^>]*>/g, ' '); // Extract text
    if (!validateCopy(textContent)) {
      console.warn('Banned words detected in generated ad. Regenerating...');
      // Could retry here, but for now just log warning
    }

    // Add Apparatus production notes in dossier format
    const now = new Date();
    const timestamp = `${now.getFullYear()}.${String(now.getMonth() + 1).padStart(2, '0')}.${String(now.getDate()).padStart(2, '0')}.${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;
    const dossierNumber = Math.floor(Math.random() * 900 + 100);
    
    const apparatusNotes = `\n<!--\n### 008 — FINAL ADVERTISEMENT\n\n**COMPILED BY:** THE APPARATUS\n**DATE:** ${timestamp}\n\n---\n\n**APPARATUS PRODUCTION NOTES:**\n\n- DOSSIER NO. ${dossierNumber}-${now.getFullYear()}\n- RE: ${brief}\n- All documents received. The Cell's transmittal arrived in parts. This appears to be intentional.\n- Burl has requested adjustments. Adjusting.\n- Dr. Poole has submitted revisions to his framework. This is the fourth revision. The changes are minor. The document is now longer.\n- HTML generated ${timestamp}\n- All elements compiled per Committee approval\n- Visual direction applied per Burl's specifications\n- Copy integrated per The Cell's transmittal\n- Framework applied per Dr. Poole's system\n- Production schedule maintained per Nadya's plan\n\nREADY FOR REVIEW—${timestamp}\n-->`;

    return cleanedHtml + apparatusNotes;
  } catch (error) {
    console.error('Error generating ad with OpenAI:', error);
    return generateFallbackAd(brief, brandInfo);
  }
}

/**
 * Generates HTML template following THE HOUSE AESTHETIC
 * Aesthetic: Soviet forms, legal paperwork, truth over beauty
 * NOT: Rainbow chaos, Comic Sans, startup energy
 * 
 * Based on the reference implementation: "47 Decisions" ad structure
 */
export function generateAdHTML(adData: {
  headline: string;
  body: string;
  bodySecondary?: string;
  tagline: string;
  visual: string;
  client: string;
  clientLocation?: string;
  clientSince?: string;
}, brandInfo?: import('../types').BrandInfo): string {
  const { headline, body, bodySecondary, tagline, visual, client, clientLocation, clientSince } = adData;
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${client} — ADHDAI</title>
  <style>
    /* 
     * FERAL CREATIVE COLLECTIVE — HOUSE STYLE
     * 
     * THIS IS THE CORRECT AESTHETIC:
     * - Soviet forms, legal paperwork
     * - Document texture, things photocopied twice
     * - Truth over beauty
     * - Limited palette (paper, ink, gray)
     * - Typography as character
     * 
     * THIS IS NOT:
     * - Rainbow gradients
     * - Comic Sans
     * - Pulsing animations
     * - Startup energy
     * - "Disruptive paradigm-shifting blockchain"
     */
    
    @import url('https://fonts.googleapis.com/css2?family=Courier+Prime:wght@400;700&family=Source+Serif+4:ital,wght@0,400;0,600;1,400&family=Inter:wght@400;500&display=swap');
    
    :root {
      --paper: #F7F6F4;
      --paper-white: #FFFFFF;
      --ink: #1a1a1a;
      --ink-faded: #4a4a4a;
      --ink-light: #7a7a7a;
      --ink-ghost: #a0a0a0;
      --rule: #d0d0d0;
      ${brandInfo?.brandColors.primary ? `--brand-primary: ${brandInfo.brandColors.primary};` : ''}
      ${brandInfo?.brandColors.secondary ? `--brand-secondary: ${brandInfo.brandColors.secondary};` : ''}
      ${brandInfo?.brandColors.accent ? `--brand-accent: ${brandInfo.brandColors.accent};` : ''}
    }
    
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    html {
      font-size: 16px;
    }
    
    body {
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
      background: var(--paper);
      color: var(--ink);
      min-height: 100vh;
      line-height: 1.5;
      
      /* Paper texture - very subtle grain, like a form */
      background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.8' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)' opacity='0.025'/%3E%3C/svg%3E");
    }
    
    .ad-container {
      max-width: 720px;
      margin: 0 auto;
      padding: 80px 48px;
      min-height: 100vh;
      display: flex;
      flex-direction: column;
    }
    
    /* ================================================
       THE HEADLINE
       Weight of a legal document. Typewriter energy.
       Like something you'd find in a filing cabinet.
       ================================================ */
    .headline {
      font-family: ${brandInfo?.brandFonts?.heading ? `'${brandInfo.brandFonts.heading}', ` : ''}'Courier Prime', 'Courier New', Courier, monospace;
      font-size: 32px;
      font-weight: 700;
      line-height: 1.25;
      letter-spacing: -0.01em;
      margin-bottom: 48px;
      color: ${brandInfo?.brandColors.primary ? 'var(--brand-primary)' : 'var(--ink)'};
      text-transform: uppercase;
      ${brandInfo?.brandColors.primary ? 'border-bottom: 2px solid var(--brand-primary); padding-bottom: 8px;' : ''}
    }
    
    /* ================================================
       THE VISUAL ELEMENT
       This is the argument made visible.
       The list of decisions, fading into overwhelm.
       ================================================ */
    .decisions-container {
      background: var(--paper-white);
      border: 1px solid var(--rule);
      padding: 32px;
      margin-bottom: 48px;
      flex: 1;
    }
    
    .decisions-list {
      font-family: 'Courier Prime', monospace;
      font-size: 13px;
      line-height: 1.7;
      color: var(--ink-faded);
      list-style: none;
      columns: 1;
    }
    
    .decisions-list li {
      margin-bottom: 2px;
      padding-left: 28px;
      position: relative;
    }
    
    .decisions-list li::before {
      content: attr(data-num) ".";
      position: absolute;
      left: 0;
      color: var(--ink-light);
      font-size: 11px;
    }
    
    /* The fade: legible → squinting → almost gone */
    .decisions-list li:nth-child(n+15) {
      font-size: 12px;
      color: var(--ink-light);
    }
    .decisions-list li:nth-child(n+25) {
      font-size: 11px;
      opacity: 0.7;
    }
    .decisions-list li:nth-child(n+35) {
      font-size: 10px;
      opacity: 0.5;
    }
    .decisions-list li:nth-child(n+42) {
      font-size: 9px;
      opacity: 0.35;
    }
    .decisions-list li:nth-child(n+46) {
      font-size: 8px;
      opacity: 0.25;
    }
    
    /* ================================================
       THE BODY COPY
       Relief after the list. Serif. Warm.
       The human voice after the bureaucracy.
       ================================================ */
    .body-copy {
      font-family: ${brandInfo?.brandFonts?.body ? `'${brandInfo.brandFonts.body}', ` : ''}'Source Serif 4', Georgia, serif;
      font-size: 20px;
      line-height: 1.55;
      color: var(--ink);
      margin-bottom: 16px;
      max-width: 540px;
    }
    
    .body-copy-secondary {
      font-family: 'Source Serif 4', Georgia, serif;
      font-size: 16px;
      font-style: italic;
      line-height: 1.5;
      color: var(--ink-faded);
      margin-bottom: 48px;
    }
    
    /* ================================================
       THE TAGLINE
       Stands alone. Sounds like speech.
       Something a person would actually say.
       ================================================ */
    .tagline {
      font-family: 'Source Serif 4', Georgia, serif;
      font-size: 15px;
      font-weight: 600;
      color: var(--ink);
      margin-bottom: 48px;
      letter-spacing: 0.01em;
    }
    
    /* ================================================
       CLIENT INFO
       Minimal. Corner of the page. Authority.
       ================================================ */
    .client-info {
      margin-top: auto;
      padding-top: 32px;
      border-top: 2px solid ${brandInfo?.brandColors.primary ? 'var(--brand-primary)' : 'var(--rule)'};
    }
    
    .client-name {
      font-family: 'Inter', sans-serif;
      font-size: 13px;
      font-weight: 500;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--ink);
      margin-bottom: 4px;
    }
    
    .client-location {
      font-family: 'Inter', sans-serif;
      font-size: 12px;
      color: var(--ink-light);
      letter-spacing: 0.02em;
    }
    
    .client-since {
      font-family: 'Source Serif 4', Georgia, serif;
      font-size: 12px;
      font-style: italic;
      color: var(--ink-ghost);
      margin-top: 8px;
    }
    
    /* ================================================
       RESPONSIVE
       ================================================ */
    @media (max-width: 600px) {
      .ad-container {
        padding: 48px 24px;
      }
      .headline {
        font-size: 24px;
      }
      .decisions-container {
        padding: 20px;
      }
      .body-copy {
        font-size: 18px;
      }
    }
    
    /* ================================================
       PRINT
       ================================================ */
    @media print {
      body {
        background: white;
      }
      .ad-container {
        padding: 40px;
        max-width: none;
      }
    }
  </style>
</head>
<body>
  <div class="ad-container">
    
    <h1 class="headline">${headline}</h1>
    
    <div class="decisions-container">
      ${visual}
    </div>
    
    <p class="body-copy">${body}</p>
    ${bodySecondary ? `<p class="body-copy-secondary">${bodySecondary}</p>` : ''}
    
    <p class="tagline">${tagline}</p>
    
    <div class="client-info">
      <div class="client-name">${client}</div>
      ${clientLocation ? `<div class="client-location">${clientLocation}</div>` : ''}
      ${clientSince ? `<div class="client-since">${clientSince}</div>` : ''}
      ${!clientLocation && !clientSince ? '<div class="client-location">Produced by ADHDAI</div>' : ''}
    </div>
    
  </div>
</body>
</html>`;
}

/**
 * Fallback template-based ad generation when API is unavailable
 * Follows THE HOUSE AESTHETIC: document/form style, not startup style
 */
function generateFallbackAd(brief: string, brandInfo?: import('../types').BrandInfo): string {
  const now = new Date();
  const timestamp = `${now.getFullYear()}.${String(now.getMonth() + 1).padStart(2, '0')}.${String(now.getDate()).padStart(2, '0')}.${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;
  const dossierNumber = Math.floor(Math.random() * 900 + 100);
  
  return generateAdHTML({
    headline: 'BRIEF REQUIRES PROCESSING',
    body: 'Brief received. The Apparatus was unable to complete compilation.',
    bodySecondary: 'Manual review required.',
    tagline: 'Processing. Stand by.',
    visual: `<ol class="decisions-list">
      <li data-num="1">Dossier initiated but not complete</li>
      <li data-num="2">The Collective requires manual intervention</li>
    </ol>`,
    client: 'ADHDAI'
  }, brandInfo) + `<!--
### 008 — FINAL ADVERTISEMENT

**COMPILED BY:** THE APPARATUS
**DATE:** ${timestamp}

---

**APPARATUS PRODUCTION NOTES:**

- DOSSIER NO. ${dossierNumber}-${now.getFullYear()}
- RE: ${brief}
- Fallback template applied ${timestamp}
- API unavailable—template generated per standard procedure
- All elements compiled per Committee approval
- Visual direction applied per Burl's specifications
- Copy integrated per The Cell's transmittal

READY FOR REVIEW—${timestamp}
-->`;
}
